trigger:
- main  # Déclenchement du pipeline à chaque modification de la branche 'main'

pool:
  name: 'default'  # Utilisation du pool d'agents par défaut

variables:
  azureSubscription: 'AzureServiceConnection'  # Nom du service de connexion Azure dans Azure Devops
  resourceGroup: 'resourceGroup'  # Nom du groupe de ressources à créer
  location: 'canadacentral'  # Région pour le groupe de ressources

steps:
# Étape 1 : Créer le Resource Group (si nécessaire)
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Création du groupe de ressources si nécessaire..."
      az group create --name $(resourceGroup) --location $(location)

# Étape 2 : Déployer le Storage Account avec ARM Template
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(azureSubscription)
    resourceGroupName: $(resourceGroup)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'  # Chemin vers votre fichier de template JSON
    csmParametersFile: 'azuredeploy.parameters.json'  # Chemin vers votre fichier de paramètres JSON
    deploymentMode: 'Incremental'  # Déploiement incrémental pour ne pas supprimer les ressources existantes
