trigger:
- none  # Déclenchement sur la branche 'main'

pool:
  name: 'default'  # Utilise le pool par défaut

steps:
# Étape 1 : Validation des fichiers ARM Template (Syntaxe JSON)
- task: AzureCLI@2
  inputs:

    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Validation de la syntaxe des ARM templates..."
      az deployment group validate \
        --resource-group RG_Devoir_2 \
        --template-file storage-account/azuredeploy.json \
        --parameters @storage-account/azuredeploy.parameters.json

      az deployment group validate \
        --resource-group RG_Devoir_2 \
        --template-file function-app/azuredeploy.json \
        --parameters @function-app/azuredeploy.parameters.json

# Étape 2 : Compilation des fichiers ARM Template (Optionnel)
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Compilation ou minification des fichiers ARM templates..."
      # Ajoutez des scripts spécifiques pour modifier ou valider davantage vos fichiers JSON si nécessaire.
