trigger:
- main  # Déclenchement du pipeline sur la branche 'main'

pool: 
  name: 'default'  # Pool d'agents par défaut

variables:
  azureSubscription: 'NomDuServiceAzure'  # Nom du service de connexion Azure
  resourceGroup: 'NomDuGroupeRessource'  # Nom du groupe de ressources Azure
  storageAccountName: 'NomDuStorageAccount'  # Nom du Storage Account
  functionAppName: 'NomDeLaFunctionApp'  # Nom de la Function App
  buildConfiguration: 'Release'  # Configuration pour la compilation (Debug/Release)

steps:
# Étape 1 : Validation et compilation des projets MSBuild
- task: VSBuild@1
  inputs:
    solution: '**/*.csproj'  # Localisation des fichiers MSBuild à compiler
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    platform: 'Any CPU'
    configuration: '$(buildConfiguration)'

# Étape 2 : Déploiement du Storage Account
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Validation et création du groupe de ressources si nécessaire..."
      az group exists --name $(resourceGroup) || az group create --name $(resourceGroup) --location eastus

      echo "Déploiement du Storage Account..."
      az storage account create --name $(storageAccountName) --resource-group $(resourceGroup) --location eastus --sku Standard_LRS

# Étape 3 : Déploiement de la Function App
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Déploiement de la Function App..."
      az functionapp create --resource-group $(resourceGroup) --consumption-plan-location eastus --name $(functionAppName) --storage-account $(storageAccountName) --runtime dotnet --runtime-version 6

# Étape 4 : Déployer le code de la Function App
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Déploiement du code vers la Function App..."
      az functionapp deployment source config-zip --resource-group $(resourceGroup) --name $(functionAppName) --src $(Build.ArtifactStagingDirectory)/FunctionApp.zip

# Étape 5 : Validation de la configuration
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Vérification des ressources déployées..."
      az storage account show --name $(storageAccountName) --resource-group $(resourceGroup)
      az functionapp show --name $(functionAppName) --resource-group $(resourceGroup)
