# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"

variables:
  - name: resourceGroupName
    value: 'RG_Devoir_2'
  - name: rgLocation
    value: 'Canada Central'
    # Project folder name for the Infrastructure
  #- name: AzureAppInfrastructure
  #  value: 'InfrastructureBlob'
    # Project folder name for the Azure Function
  - name: AzureAppFunction
    value: 'function'
    # Name of the Infrastructure Resource (Blob)
  #- name: AzureBlob
  #  value: 'blobfunctionguro'
  #- name: AzureBlobContainerName
  #  value: 'blob'
  - name: AzureFunctionAppName
    value: 'myfunctionappdevoir2'
  #- name: BlobString
  #  value: 'patate'

jobs:
- job : StorageAccount
  steps:
  # - bash: echo "Storage Account"
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Abo Devoir 2(dde5eab5-8f95-425b-b698-3a605a01ad88)'
      subscriptionId: 'dde5eab5-8f95-425b-b698-3a605a01ad88'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'RG_Devoir_2'
      location: 'Canada Central'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\StorageAccount\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\StorageAccount\azuredeploy.parameters.json'
      deploymentMode: 'Incremental'
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Abo Devoir 2(dde5eab5-8f95-425b-b698-3a605a01ad88)'
      subscriptionId: 'dde5eab5-8f95-425b-b698-3a605a01ad88'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'RG_Devoir_2'
      location: 'Canada Central'
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.SourcesDirectory)\FunctionApp\azuredeploy.json'
      csmParametersFile: '$(Build.SourcesDirectory)\FunctionApp\azuredeploy.parameters.json'
      deploymentMode: 'Incremental'
